### ISSUE TITLE
出现这种问题

### ISSUE THREAD

**Issue by xiaoyanguoke** [BlueCocoa/WirelessKit#1]
case `uname` in RaspberryPi*) g++ -Os -I./WirelessKit -std=c++14 -fPIC -D__RASPBIAN__=1 -c WirelessKit/WirelessKit.cpp -o obj/WirelessKit.o ;; *) g++ -Os -I./WirelessKit -std=c++14 -fPIC -c WirelessKit/WirelessKit.cpp -o obj/WirelessKit.o ;; esac
In file included from WirelessKit/WirelessKit.cpp:10:0:
WirelessKit/WirelessKit.hpp:14:18: fatal error: pcap.h: No such file or directory
 #include <pcap.h>
                  ^
compilation terminated.
Makefile:19: recipe for target 'lib/libWirelessKit.a' failed
make: *** [lib/libWirelessKit.a] Error 1

**Comment by BlueCocoa** [comment]
Please install `libpcap`, usually you can execute this in terminal (if your OS uses APT for package management)
```
$ [sudo] apt-get install libpcap-dev
```
